# Generated by Django 5.2 on 2025-04-05 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='Address',
            field=models.CharField(default='Milad Tower - Tehran', max_length=500),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDateTime', models.DateTimeField()),
                ('Seats', models.IntegerField()),
                ('Status', models.IntegerField(choices=[('Start', 'Ticket sales have started'), ('End', 'Ticket sales have ended'), ('Cancel', 'This concert session has been cancelled'), ('Sales', 'Selling tickets')])),
                ('ConcertModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.concertmodel')),
                ('LocationModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.locationmodel')),
            ],
        ),
    ]
