# Generated by Django 5.1.6 on 2025-04-19 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketSales', '0003_profilemodel_concertmodel_poster_ticketmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertmodel',
            options={'verbose_name': 'Concert', 'verbose_name_plural': 'Concerts'},
        ),
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='ticketmodel',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'Concert Session', 'verbose_name_plural': 'Concert Sessions'},
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Lenght',
            field=models.IntegerField(verbose_name='Concert Duration'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Title of the Concert'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='Poster',
            field=models.ImageField(null=True, upload_to='ConcertImages/', verbose_name='Upload Concert Poster'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='SingerName',
            field=models.CharField(max_length=100, verbose_name='Performer Name'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Address',
            field=models.CharField(default='Milad Tower - Tehran', max_length=500, verbose_name='Address of the Concert Venue'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Capacity',
            field=models.IntegerField(verbose_name='Capacity of the Venue'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Venue Name'),
        ),
        migrations.AlterField(
            model_name='locationmodel',
            name='Phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Family',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Gender',
            field=models.IntegerField(choices=[(1, 'Man'), (2, 'Woman')], verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='ProfileImage',
            field=models.ImageField(null=True, upload_to='ProfileImages/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Type of Ticket'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='Price',
            field=models.IntegerField(verbose_name='Concert Ticket Price'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='ProfileModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.profilemodel', verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='TicketImage',
            field=models.ImageField(upload_to='TicketImages/', verbose_name='Concert Ticket Image'),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='TimeModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.timemodel', verbose_name='Concert Session Info'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='ConcertModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.concertmodel', verbose_name='Performer'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='LocationModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TicketSales.locationmodel', verbose_name='Concert Venue'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Seats',
            field=models.IntegerField(verbose_name='Number of Seats'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='StartDateTime',
            field=models.DateTimeField(verbose_name='Concert Start Time'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Ticket sales have started'), (2, 'Ticket sales have ended'), (3, 'This concert session has been cancelled'), (4, 'Selling tickets')], verbose_name='Concert Session Status'),
        ),
    ]
